app:
    type:     annotation
    resource: "@AppBundle/Controller/Site/"

comments:
    type:     rest
    prefix: _/
    resource: "@AppBundle/Controller/WebApi/CommentsController.php"

gregwar_captcha_routing:
    resource: "@GregwarCaptchaBundle/Resources/config/routing/routing.yml"